### ISSUE TITLE
[BUG] - semanticColors are not extended by custom themes

### ISSUE THREAD

**Issue by tlow92** [nextui-org/nextui#1605]
### NextUI Version

2.1.3

### Describe the bug

When a custom theme was defined, there is no way to access the semantic colors from javascript.
`semanticColors.light.primary[400]` returns the default primary color, but `semanticColors` only has `light`/`dark`.

So if a custom theme named `customTheme` is added, `semanticColors.customTheme.primary[400]` does not exist.

### Steps to Reproduce the Bug or Issue

1. Define custom theme in `tailwind.config.js` e.g. https://nextui.org/docs/customization/create-theme#add-the-new-theme-to-the-plugin
2. Try to access colors in javascript through `semanticColors.purple-dark`

### Expected behavior

I should be able to access the custom theme colors in JS somehow, as some third party libraries e.g. that use canvas do not provide a way to pass colors through classnames or css vars.

My current workaround is: 
* Have a json with the whole theme configuration that is passed to `nextui()`
* In the components the current theme is parsed through html `class`/`data-theme` prop or with ThemeProvider from next-themes.
* The current theme is then mapped to the static json from step 1

### Operating System Version

macOS

### Browser

Chrome

**Comment by LPSebi** [comment]
# +1
## Also DEFAULT doesn't exist for some reason

![image](https://github.com/nextui-org/nextui/assets/52174534/bfad856e-4a31-4cd0-a659-9d257b0b0d90)

![image](https://github.com/nextui-org/nextui/assets/52174534/6253349e-dbac-4d51-9693-b19717600c1a)

**Comment by bleo-m** [comment]
Are there any updates on this? I also am running into the error where DEFAULT does not exist @LPSebi

**Comment by LPSebi** [comment]
> Are there any updates on this? I also am running into the error where DEFAULT does not exist @LPSebi 

make sure all of the packages are updated. I fixed it somehow. Maybe by reinstalling the packages

**Comment by monkey-denky** [comment]
I have a similar issue when trying to set semantic color variant based on theme with tailwind:
```
className="text-primary custom-theme:text-primary-300"
```

This custom theme color is not applied

**Comment by mdtausifiqbal** [comment]
My issue is when I am setting different primary DEFAULT colors and referencing it from javascript using `semanticColors.light.primary.DEFAULT` then the output is a default blue color (#006FEE).

**Comment by hazirmagron** [comment]
This still doesn't seem to be fixed (v.2.2.9)
<img width="470" alt="Screenshot 2024-02-08 at 21 41 15" src="https://github.com/nextui-org/nextui/assets/13097564/225429b2-c5ba-49f6-bce8-4c31481a4063">

**Comment by MarcelloPaiva** [comment]
> This still doesn't seem to be fixed (v.2.2.9) <img alt="Screenshot 2024-02-08 at 21 41 15" width="470" src="https://private-user-images.githubusercontent.com/13097564/303477637-225429b2-c5ba-49f6-bce8-4c31481a4063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODAyMDcsIm5iZiI6MTcxMDc3OTkwNywicGF0aCI6Ii8xMzA5NzU2NC8zMDM0Nzc2MzctMjI1NDI5YjItYzViYS00OWY2LWJjZTgtNGMzMTQ4MWE0MDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE2MzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZDA2NTFlZjlhOTY2ZmMwODI0Y2Q3YWQ0NGE5Y2VmMDNlYWE2M2E0NmM0ZWFiYzY5NTFjMzFlYTJhMzFkMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8DNc6V1wzAr61RwFyisAWydTm9CaJkyIdrrnzgM6DCA">

I am having the same issue

**Comment by zachwaterstories** [comment]
Same issue here, no default on color and no custom theme propagation.

**Comment by jimhdev** [comment]
Yup same problem

> My issue is when I am setting different primary DEFAULT colors and referencing it from javascript using `semanticColors.light.primary.DEFAULT` then the output is a default blue color (#006FEE).

exactly the same issue here

**Comment by elgalia** [comment]
Same issue here :/

**Comment by LeakedDave** [comment]
Hey it would be great to have customized colors supported and accessible from JavaScript

**Comment by necheporenko** [comment]
any updates with this issue?

**Comment by marshmn** [comment]
I just ran into this issue too...

Given that this is a long standing limitation it seems, the docs could at least be clearer about it...

**Comment by GabrielLourenco** [comment]
> > This still doesn't seem to be fixed (v.2.2.9) <img alt="Screenshot 2024-02-08 at 21 41 15" width="470" src="https://private-user-images.githubusercontent.com/13097564/303477637-225429b2-c5ba-49f6-bce8-4c31481a4063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY5MjcsIm5iZiI6MTcyMzcyNjYyNywicGF0aCI6Ii8xMzA5NzU2NC8zMDM0Nzc2MzctMjI1NDI5YjItYzViYS00OWY2LWJjZTgtNGMzMTQ4MWE0MDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZGVkZGU3YjVlNThiYmJiYjBiY2MxOTBhYmYwYWI3M2JhYWQyOTJkNThlNGEzYjY2ZTRlOGVhNzY2Njc0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mHk5U4jzwynDOKRRbfs7WiUEN5ZjMqwOopHPGqVOHaA">
> 
> A workaround for this is to cast `ColorScale` to `any`
> 
> ```
> (semanticColors.light.secondary as any)["DEFAULT"]
> ```

I created a new type to use instead of default ColorScale:

```ts
type RealColorScale = Exclude<ColorScale, string>;
```

Now, I tried to use my new primary colors, but using semanticColors the colors applied is the default HeroUI instead of my own primary colors. All HeroUI components changes, but unfortunately the sematicColors not.

**Comment by kirilledelman** [comment]
Came here to find a workaround.

**Comment by xepozz** [comment]
Any updates?

**Comment by wingkwong** [comment]
Closing in favor of v3. If the issue is reproducible in v3, please create a new one with a minimal reproducible example.
