### ISSUE TITLE
Dark mode not applied to modal.

### ISSUE THREAD

**Issue by hosenur** [nextui-org/nextui#1769]
### NextUI Version

2.1.13

### Describe the bug

I am using NextUI with Vite, React, after setting the app to dark mode by applying the classname to  main, modals still open in light mode, even if i add the dark classname to the modal, and have a select field inside the modal the select options are still in light mode

### Steps to Reproduce the Bug or Issue

1. Setup NextUI on  a React + Vite project and set dark theme.
2. Add a modal with form
3. The modal opens in light mode.

### Expected behavior

The modal should be in dark mode, when putting form components like Select , the options of select are in light mode, also in the docs the code for multi select and single select is same.

### Operating System Version

Linux

### Browser

Chrome

**Comment by hernan-dp** [comment]
The same thing with the list of the select. Had to add dark class to className and a conditional to have it working.

**Comment by ttiras** [comment]
Same, i fixed the modal with checking the theme manually and adding styles accordingly.

**Comment by jrgarciadev** [comment]
Hey guys make sure you're adding the theme name to the root element.

E.g. with the mentioned "issue": https://codesandbox.io/p/sandbox/pqn6jr?file=%2FApp.jsx%3A1%2C1&utm_medium=sandpack

E.g. Applying the `dark` theme class to the `body` element in the `index.html` file:
https://codesandbox.io/p/sandbox/fervent-wu-wqcd4q?file=%2Findex.html&utm_medium=sandpack

I'll add a section in the docs for this, thanks!

**Comment by znareak** [comment]
> Hey guys make sure you're adding the theme name to the root element.
> 
> E.g. with the mentioned "issue": https://codesandbox.io/p/sandbox/pqn6jr?file=%2FApp.jsx%3A1%2C1&utm_medium=sandpack
> 
> E.g. Applying the `dark` theme class to the `body` element in the `index.html` file: https://codesandbox.io/p/sandbox/fervent-wu-wqcd4q?file=%2Findex.html&utm_medium=sandpack
> 
> I'll add a section in the docs for this, thanks!

Thank you, it works for me!

**Comment by unav4ila8le** [comment]
I have the same issue. Adding "dark" class to the body does not solve the problem.

**Comment by aaonhub** [comment]
Also not working for me

**Comment by JoseAlbDR** [comment]
Add the dark class to the modal, along with bg-background and text-foreground classes.
Im using Vite/React with use-dark-mode to switch between themes

```typescript
. . . 
import useDarkMode from 'use-dark-mode';
. . . 

. . . 
export default function DeleteModal({ bot }: Payload) {
const darkMode = useDarkMode();
. . . 

. . . 
return (
    <>
      <Button
        onPress={onOpen}
        isIconOnly
        aria-label="Like"
        className="bg-terciary"
      >
        <TrashCan />
      </Button>
      <Modal
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        className={`${
          darkMode.value ? 'dark' : ''
        } text-foreground bg-background border border-white`}
      >
      . . . 

```

**Comment by unav4ila8le** [comment]
> Add the dark class to the modal, along with bg-background and text-foreground classes. Im using Vite/React with use-dark-mode to switch between themes
> 
> ```ts
> . . . 
> import useDarkMode from 'use-dark-mode';
> . . . 
> 
> . . . 
> export default function DeleteModal({ bot }: Payload) {
> const darkMode = useDarkMode();
> . . . 
> 
> . . . 
> return (
>     <>
>       <Button
>         onPress={onOpen}
>         isIconOnly
>         aria-label="Like"
>         className="bg-terciary"
>       >
>         <TrashCan />
>       </Button>
>       <Modal
>         isOpen={isOpen}
>         onOpenChange={onOpenChange}
>         className={`${
>           darkMode.value ? 'dark' : ''
>         } text-foreground bg-background border border-white`}
>       >
>       . . . 
> ```

Thank you @JoseAlbDR , this is exactly what I ended up doing. I was just hoping it could have worked by default without the need to specify the class in every modal.

**Comment by frichicken** [comment]
![image](https://github.com/nextui-org/nextui/assets/44330406/a1d5ef2f-2a0e-4776-a70a-731877a8e5dd)

**Comment by riosant** [comment]
Adding text-background bg-background works but you have to tweak the text foreground color based on the theme.
for me I was using autocomplete hence tweaked the text color like below

            ```
<Modal
                isOpen={isSearchModalVisible}
                placement="top"
                classNames={{backdrop: "backdrop-blur-3xl", wrapper: `${theme.mode}`}}
                hideCloseButton
                className="mt-0 border-0 rounded-none h-screen"
                size="2xl"
                motionProps={{
                    variants: {
                        enter: {
                            y: 0,
                            opacity: 1,
                            transition: {
                                duration: 0.3,
                                ease: "easeOut",
                            },
                        },
                        exit: {
                            y: -20,
                            opacity: 0,
                            transition: {
                                duration: 0.2,
                                ease: "easeIn",
                            },
                        },
                    },
                }}
            >
                <ModalContent className="max-h-min h-min">
                    {() => (
                        <form onSubmit={handleSearch}>
                            <ModalHeader className="flex flex-row justify-between items-center gap-1 bg-background text-background">
                                <div className="dark:text-white">
                                    Search Your Favourites
                                </div>
                                <Button className="px-0 w-auto border-0 bg-transparent" variant="flat" color="danger" radius="full"
                                        onPress={() => setIsSearchModalVisible(false)}>
                                    X
                                </Button>
                            </ModalHeader>
                            <ModalBody className="relative">
                                <Autocomplete
                                    isLoading={searchSuggestionsLoader}
                                    items={searchSuggestions}
                                    label="Select a track"
                                    placeholder="Type to search..."
                                    variant="bordered"
                                    onInputChange={(e) => getSuggestions(e)}
                                    isClearable={false}
                                    className="dark:text-white"
                                >
{/* changed the text color based on different theme being used in the AutocompleteItem classnames*/}
                                    {(item, index) => (
                                        <AutocompleteItem key={`${item.name}_${Math.random().toString()}`} className="capitalize dark:text-white">
                                            {item.label}
                                        </AutocompleteItem>
                                    )}
                                </Autocomplete>
                                {/*{searchSuggestionsLoader ? <Spinner/> :
                                    <Button className="absolute right-1 top-4 text-gray-400 bg-transparent" color="flat"
                                            type="submit" title="Search now"
                                            area-label="Search now">
                                        <FontAwesomeIcon className="bg-white" icon={faSearch}/>
                                    </Button>}*/}
                            </ModalBody>
                            <ModalFooter>
                            </ModalFooter>
                        </form>
                    )}
                </ModalContent>
            </Modal>
```

**Comment by wood3n** [comment]
Just add `class="dark"` to html element, see heroui document website:

<img width="615" alt="Image" src="https://github.com/user-attachments/assets/f29d49cc-e9a9-440d-8017-0917e5cddbf5" />
