### ISSUE TITLE
[BUG] - ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by srivatsa17** [nextui-org/nextui#3188]
### NextUI Version

2.4.0

### Describe the bug

I am using the `Autocomplete` inside a `Modal` component along with `Formik` and `yup` for validation. 
1. Whenever i click on the button to open the modal, console errors out saying
```
Warning: React does not recognize the `disableAnimation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableanimation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
2. The selection is working as expected however, whenever i try to type, it errors out saying `ResizeObserver loop completed with undelivered notifications.`. This is happening with the `2.4.0` version.

I am not seeing this issue in Sandbox but just in my localhost. Why is it behaving differently with sandbox and my localhost ?
Code - [Sandbox](https://codesandbox.io/p/devbox/youthful-matan-ssgrn2)

PS: Have attached the screen recording as a zip since its large in size and github did not allow it :(.

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

Should not be seeing any error when typing inside the `Autocomplete` component

### Screenshots or Videos

[Screen Recording 2024-06-05 at 10.16.08 PM.zip](https://github.com/user-attachments/files/15593885/Screen.Recording.2024-06-05.at.10.16.08.PM.zip)

### Operating System Version

macOS

### Browser

Firefox

**Comment by wingkwong** [comment]
1. The first issue has been resolved in `v2.4.1`.
2. for the second issue, can you test with `"@nextui-org/autocomplete": "0.0.0-canary-20240604122531"`? also may try to bump the version of `react-dom` and `framer-motion`.

**Comment by srivatsa17** [comment]
> 1. The first issue has been resolved in `v2.4.1`.
> 
>     2. for the second issue, can you test with `"@nextui-org/autocomplete": "0.0.0-canary-20240604122531"`? also may try to bump the version of `react-dom` and `framer-motion`.

1. First issue is no more seen after upgrade.
2. Can you please explain how i can update the autocomplete to the version you specified and what versions you'd want me to check for react dom and framer motion. Currently i'm on `"react-dom": "^18.3.1"` and `"framer-motion": "^10.18.0"`

**Comment by wingkwong** [comment]
1. maybe you can try `"@nextui-org/react": "0.0.0-canary-20240604122531" since you install globally.
2. i think it's fine but it depends on how you set the value.

**Comment by srivatsa17** [comment]
> 1. maybe you can try `"@nextui-org/react": "0.0.0-canary-20240604122531" since you install globally.
> 2. i think it's fine but it depends on how you set the value.

I am still seeing the same issue with this version of nextui.

**Comment by srivatsa17** [comment]
Update on this issue - It is happening in just localhost, but not in prod. Any comments why this happens ? @wingkwong

**Comment by wingkwong** [comment]
No clue yet.

**Comment by srivatsa17** [comment]
Fixed in localhost as well after bumping version from `2.4.1` to `2.4.2`
