### ISSUE TITLE
[BUG] - Terminal will request to add <SSRProvider> for consistent ids

### ISSUE THREAD

**Issue by Kublick** [nextui-org/nextui#522]
### Describe the bug

Hello

After updating my project to v1.0.0-beta8 (Nextjs 12.1.5, React 17) on terminal console I get the following error.

![image](https://user-images.githubusercontent.com/39152022/172725805-d3b1eece-d978-4b93-80ad-8d8633fe4ed6.png)

On the browser console I will see that id are not matching

![image](https://user-images.githubusercontent.com/39152022/172726110-16ab3e5e-a64f-4e01-92eb-465063775dc4.png)

you can check it out at https://codesandbox.io/s/youthful-ride-s1n4hd

### Your Example Website or App

https://codesandbox.io/s/youthful-ride-s1n4hd

### Steps to Reproduce the Bug or Issue

1. Just enter codesanbox link
2. check terminal 
3. check console

### Expected behavior

There shouldnt be any errors for id's between the client and server.

### Operating System Version

Linux

### Browser

Chrome

**Comment by SaadBazaz** [comment]
Still getting this.

**Comment by KSJaay** [comment]
Started getting this again since I updated to `v1.0.0-beta.11`

**Comment by BrianGrug** [comment]
Started getting this suddenly as well

**Comment by WhitigolProd** [comment]
Getting this on `v1.0.0-beta.12`. Any fix to this?

**Comment by DevDaveJ** [comment]
Yep, Im getting this too, same version v1.0.0-beta.12

**Comment by BrianGrug** [comment]
It seems using another SSRProvider fixes the issue until a fix is pushed

**Comment by mrjomp** [comment]
Hey @jrgarciadev could you be so kind as to reopen this issue?

**Comment by st4ng** [comment]
[Adding this to my package.json fixed it:](https://github.com/nextui-org/nextui/issues/779#issuecomment-1464963799)

```
"resolutions": {
    "@react-aria/ssr": "^3.4.1"
 }
```

**Comment by benediktms** [comment]
still an issue, manual resolution still does not solve the issue for me. I also tried to manually wrap my application in the ssr component like so:
```tsx
const MyApp: AppType<AppInitialProps> = ({ Component, pageProps }) => {
  return (
    <SSRProvider>
      <NextUIProvider>
        <Component {...pageProps} />
      </NextUIProvider>
    </SSRProvider>
  );
};
```

but this doesn't help either.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).
